version: "3.9"

networks:
  web: {}

services:
  backend:
    build: ./backend
    container_name: portuguese_memorizer_backend
    expose:
      - "8000"
    volumes:
      - ./backend/app:/app/app:ro
      - ./backend/data:/app/data
    restart: unless-stopped
    networks: [web]

  frontend:
    build:
      context: ./frontend
      args:
        # теперь фронт ходит на /api через прокси
        VITE_API_BASE: /api
    container_name: portuguese_memorizer_frontend
    depends_on:
      - backend
    expose:
      - "80"
    restart: unless-stopped
    networks: [web]

  caddy:
    image: caddy:2
    container_name: olacards_caddy
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - EMAIL=admin@olacards.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [web]

volumes:
  caddy_data:
  caddy_config:
